---
title: "exploration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exploration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fusen.squirrels)
```

<!--

# Description of your package

This will fill the description of your package.
Add this chunk using `fusen::description_chunk()`
--> 


# Read data

<!-- Store your dataset in a directory named "inst/" at the root of your project -->
<!-- Use it for your tests in this Rmd thanks to `load_all()` to make it available
and `system.file()` to read it in your examples 
-->


# Check the validity of the entry dataset

```{r example-1}
datafile <- system.file("nyc_squirrels_sample.csv", package = "fusen.squirrels")
nyc_squirrels <- read.csv(datafile)
nyc_squirrels_ok <- check_data_integrity(nyc_squirrels)
```

# Inflate your package

You're one inflate from paper to box.
Build your package from this very Rmarkdown using `fusen::inflate()`


```{r eval = FALSE}
fusen::inflate(rmd = here::here("dev/dev_history.Rmd"))
```

- Verify your `"DESCRIPTION"` file has been updated
- Verify your function is in `"R/"` directory
- Verify your test is in `"tests/testthat/"` directory
- Verify this Rmd appears in `"vignettes/"` directory

